### PR TITLE
Call API to send bonuses

### LINKED ISSUE #829: Call API to send bonuses
Inside `SendBonus.js` line 28

```js
const handleSubmitPayments = async (bonusPayments) => {
        const sentBonusInfo = { succeeded: [], failed: [] }
        await Promise.all(bonusPayments.map(bp => {
            try {
                if (!bp.contributor.wallet) {
                    throw new Error('User does not have a wallet setup')
                }
                if (bp.contributor.wallet.invoice_macaroon != null) {
                    // TODO: Implement send bonus through advanced setup (wait for response)
                    sentBonusInfo.succeeded.push(bp)
                } else if (bp.contributor.wallet.onchain_address != null) {
                    // TODO: Implement send bonus onchain (wait for response)
                    sentBonusInfo.succeeded.push(bp)
                }
            } catch (error) {
                console.log('An error occurred: ' + error)
                sentBonusInfo.failed.push(bp)
            }
        }))
        setSentBonuses(sentBonusInfo)
    }
```
if a transaction fails make sure it s added to `sentBonusInfo.failed` but keep processing the rest of the pending transactions

This information is displayed in the `SendBonusSuccessful` component

### PR DESCRIPTION
**Pull request by Ovifer13**
**Issue #829**

- [x] Call API when sending bonuses
- [x] Handle successful and failed payments

**Proof**
image
image

### CODE REVIEW

**Review by otech47 — CHANGES_REQUESTED** [review]
refactor [ContributorInput](https://github.com/setlife-network/trinary/pull/836/files#diff-536ac3ddd26595820d1be866c1a101ae5552f991ff3f989f67db0f4ebfe0c917R43) in the PaymentType schema to disambiguate it

i suggest
```
input ContributorBonus {
  contributor_id: Int!,
  amount_to_pay: Int!,
}
```

**Review by otech47 — CHANGES_REQUESTED** [review]
For the sendPayment function, the `contributors` could be more explicit as `contributorsToPay`

File: api/schema/resolvers/PaymentResolver.js [hunk 1]
```diff
@@ -173,9 +173,10 @@ module.exports = {
             const invoices = await Promise.all(wallets.map(async (wallet, i) => {
                 if (wallet.dataValues.invoice_macaroon) {
                     const invoice = await lnd.addInvoice(wallet.dataValues.lnd_host, wallet.dataValues.lnd_port, wallet.dataValues.invoice_macaroon, amounts[i])
-                    return invoice.payment_request
+                    return { contributorId: wallet.dataValues.contributor_id, payment_request: invoice.payment_request }
```
Comment (otech47) [inline api/schema/resolvers/PaymentResolver.js]: use newliens here for readability

File: api/schema/resolvers/PaymentResolver.js [hunk 2]
```diff
@@ -187,9 +188,9 @@ module.exports = {
                 const lndInvoices = invoices.filter(invoice => invoice !== null)
     
                 const payLndInvoices = async () => lndInvoices.map(async invoice => {
-                    return reflect(btcPayServer.payLightningInvoice(invoice))
+                    return reflect(btcPayServer.payLightningInvoice(invoice.payment_request))
                         .then(result => {
-                            return result.status === 'fulfilled' ? result.value : { error: result.reason.message, status: result.status }
+                            return result.status === 'fulfilled' ? { contributorId: invoice.contributorId, ...result.value } : { error: result.reason.message, status: result.status }
```
Comment (otech47) [inline api/schema/resolvers/PaymentResolver.js]: use newliens here for readability

File: api/schema/resolvers/PaymentResolver.js [hunk 3]
```diff
@@ -200,7 +201,7 @@ module.exports = {
                 const payOnChain = async () => onChainAddresses.map(async receiver => {
                     return reflect(btcPayServer.createOnChainTransaction(receiver.address, String(receiver.amount / 100000000)))
                         .then(result => {
-                            return result.status === 'fulfilled' ? result.value : { error: result.reason.message, status: result.status }
+                            return result.status === 'fulfilled' ? { contributorId: receiver.contributorId, ...result.value } : { error: result.reason.message, status: result.status }
```
Comment (otech47) [inline api/schema/resolvers/PaymentResolver.js]: use newliens here for readability

File: srcv2/components/SendBonus.js [hunk 4]
```diff
@@ -27,23 +27,39 @@ const SendBonus = (props) => {
...
+            variables: {
+                contributors: contributorsWithWallets
+            }
+        })
+        bonusSent.data.sendPayment.map(bs => {
+            try {
+                if (bs.error) {
+                    throw new Error('Transaction error')
+                } else {
+                    const paymentSucced = bonusPayments.filter(item => item.contributor.id === bs.contributorId)
```
Comment (otech47) [inline srcv2/components/SendBonus.js]: fix typo `paymentSucced`

**Review by otech47 — APPROVED** [review]
